export type Lang = "kz" | "ru";
export const sections = ["about", "subscribers", "tariffs", "outages", "news", "appeals", "contacts", "privacy", "readings", "payment", "search"] as const;
export type Section = typeof sections[number];
export const sourceLinks = {
  enterprise: "https://su-zhuiesi.kz/consumers/",
  registry: "https://satypalu.gov.kz/kz/registry/show_supplier/17153",
  gov: "https://www.gov.kz/memleket/entities/kyzylorda-energy/press/news/details/1070937",
  newSite: "https://qyzylordasu.kz/",
  newsWorkers: "https://qyzylordasu.kz/%d1%81%d1%83-%d1%88%d0%b0%d1%80%d1%83%d0%b0%d1%88%d1%8b%d0%bb%d1%8b%d2%93%d1%8b-%d2%9b%d1%8b%d0%b7%d0%bc%d0%b5%d1%82%d0%ba%d0%b5%d1%80%d0%bb%d0%b5%d1%80%d1%96%d0%bd%d0%b5-%d2%9b%d2%b1%d1%80%d0%bc/",
  newsOpenness: "https://qyzylordasu.kz/%d0%b0%d1%88%d1%8b%d2%9b%d1%82%d1%8b%d2%9b-%d2%9b%d0%b0%d2%93%d0%b8%d0%b4%d0%b0%d1%82%d1%8b%d0%bd%d0%b0-%d0%b1%d0%b0%d2%93%d1%8b%d1%82%d1%82%d0%b0%d0%bb%d2%93%d0%b0%d0%bd-%d0%ba%d0%b5%d0%b7%d0%b4/",
  tariff2026: "https://su-zhuiesi.kz/ru/consumers/160-tarify-gkp-na-phv-kyzylorda-su-zhujesi-po-uslugam-podacha-vody-po-raspredelitelnym-setjam-i-po-otvodu-i-ochistke-stochnyh-vod-vvodimye-na-period-s-25-maja-2026-goda-po-30-aprelja-2027-goda.html",
  tariffAmendment: "https://su-zhuiesi.kz/ru/consumers/168-tarif-predprijatija.html",
  standardContract: "https://su-zhuiesi.kz/ru/consumers/161-tipovoj-dogovor-na-predostavlenie-uslug-vodosnabzhenija-i-ili-vodootvedenija.html",
  report2026: "https://su-zhuiesi.kz/ru/consumers/167-shzh-yzylorda-su-zhjesi-mkk-ny-2026-zhyldy-mamyr-mausym-ajlarynda-krsetilgen-yzmetter-bojynsha-esebi.html",
  facebook: "https://www.facebook.com/kizylorda.su",
  instagram: "https://www.instagram.com/p/DPTG8zciBqU/",
  telegram: "https://t.me/QSuJbot",
};
export const common = {
  kz: {
    name:"Қызылорда су жүйесі", subtitle:"Сумен жабдықтау және су бұру", nav:{about:"Кәсіпорын туралы",subscribers:"Тұтынушыларға",tariffs:"Тарифтер",outages:"Ажыратулар",news:"Жаңалықтар",appeals:"Өтініштер",contacts:"Байланыс",privacy:"Дербес деректер саясаты",readings:"Көрсеткіш беру",payment:"Төлем",search:"Іздеу"},
    home:"Басты бет", heroTitle:"Қала өмірінің негізі — сенімді су қызметі",heroText:"Қызылорда тұрғындарына сумен жабдықтау және су бұру қызметтері туралы қажетті ақпарат бір жерде.", heroCard:"Маңызды хабарландырулар",heroCardTitle:"Ажыратулар туралы ақпарат",heroCardText:"Жедел деректер көзі қосылғаннан кейін өзекті хабарламалар осы жерде жарияланады.",details:"Толығырақ", statusTitle:"Ажыратулар туралы жедел деректер қосылмаған",statusText:"Бұл ағымдағы ажыратулар жоқ дегенді білдірмейді.", quick:"Қажетті қызметтер", quickDesc:"Тұрғындарға арналған негізгі ақпарат пен қызметтер", readings:"Көрсеткіш беру", payment:"Қызмет ақысын төлеу", tariffs:"Тарифтерді қарау", appeals:"Өтініш жіберу", notConnected:"Сервис әлі қосылмаған", introTitle:"Қала инфрақұрылымының күнделікті жұмысы",introText:"Кәсіпорын Қызылорда қаласының тұтынушыларын ауыз сумен қамтамасыз ету және сарқынды суларды бұру мен тазарту бағытында жұмыс істейді.", water:"Ауыз су",waterSub:"сумен жабдықтау",sewer:"Су бұру",sewerSub:"кәріз қызметі",newsTitle:"Жаңалықтар мен хабарландырулар",viewAll:"Барлығын көру",verified:"Расталған мәлімет",required:"Толтыру қажет",demo:"Үлгі материал",source:"Дереккөз",checked:"Тексерілген күні: 23.09.2026", emergency:"Авариялық-диспетчерлік қызмет", hours:"тәулік бойы", callCenter:"Call-орталық",workHours:"Дс–Жм, 08:00–18:00",address:"Қызылорда қаласы, Желтоқсан көшесі, 156",footerInfo:"Ресми деректер мен қызметтер іске қосылған сайын сайт жаңартылады.",searchPlaceholder:"Сайттан іздеу...",noResults:"Нәтиже табылмады",close:"Жабу", filters:"Сүзгілер",all:"Барлығы",planned:"Жоспарлы",emergencyType:"Авариялық",active:"Ағымдағы",completed:"Аяқталған",unknown:"Деректер көзі қосылмаған",back:"Артқа", send:"Өтінішті тексеру",validation:"Өрістерді толтырыңыз және келісімді растаңыз.",formBlocked:"Өтініш қабылдау жүйесі әлі қосылмаған. Деректер жіберілмеді. Кәсіпорынмен байланысу үшін расталған телефон нөмірлерін пайдаланыңыз.",policyDraft:"Жоба: кәсіпорынның келісуін талап етеді.",noticeDetail:"Хабарлама үлгісі",noNews:"Жаңалықтар редакциялық жүйе қосылғаннан кейін жарияланады."
  },
  ru: {
    name:"Қызылорда су жүйесі", subtitle:"Водоснабжение и водоотведение", nav:{about:"О предприятии",subscribers:"Абонентам",tariffs:"Тарифы",outages:"Отключения",news:"Новости",appeals:"Обращения",contacts:"Контакты",privacy:"Политика персональных данных",readings:"Передать показания",payment:"Оплата",search:"Поиск"},
    home:"Главная",heroTitle:"Надёжное водоснабжение для жизни города",heroText:"Необходимая информация о водоснабжении и водоотведении для жителей Кызылорды в одном месте.",heroCard:"Важные уведомления",heroCardTitle:"Информация об отключениях",heroCardText:"Актуальные сообщения появятся здесь после подключения оперативного источника данных.",details:"Подробнее",statusTitle:"Оперативные данные об отключениях не подключены",statusText:"Это не означает, что сейчас нет отключений.",quick:"Полезные разделы",quickDesc:"Основная информация и услуги для жителей",readings:"Передать показания",payment:"Оплатить услуги",tariffs:"Узнать тарифы",appeals:"Подать обращение",notConnected:"Сервис пока не подключён",introTitle:"Ежедневная работа городской инфраструктуры",introText:"Предприятие обеспечивает потребителей Кызылорды питьевой водой, а также занимается отведением и очисткой сточных вод.",water:"Питьевая вода",waterSub:"водоснабжение",sewer:"Водоотведение",sewerSub:"канализация",newsTitle:"Новости и объявления",viewAll:"Смотреть все",verified:"Подтверждённые сведения",required:"Требуется заполнение",demo:"Демонстрационный материал",source:"Источник",checked:"Дата проверки: 23.09.2026",emergency:"Аварийно-диспетчерская служба",hours:"круглосуточно",callCenter:"Колл-центр",workHours:"Пн–Пт, 08:00–18:00",address:"г. Кызылорда, ул. Желтоксан, 156",footerInfo:"Сайт обновляется по мере подключения официальных данных и сервисов.",searchPlaceholder:"Поиск по сайту...",noResults:"Ничего не найдено",close:"Закрыть",filters:"Фильтры",all:"Все",planned:"Плановые",emergencyType:"Аварийные",active:"Текущие",completed:"Завершённые",unknown:"Источник данных не подключён",back:"Назад",send:"Проверить обращение",validation:"Заполните поля и подтвердите согласие.",formBlocked:"Система приёма обращений пока не подключена. Данные не отправлены. Для связи с предприятием используйте подтверждённые телефоны.",policyDraft:"Проект: требует согласования предприятием.",noticeDetail:"Шаблон уведомления",noNews:"Новости будут опубликованы после подключения редакционной системы."
  }
} as const;

export const demoNews = [
  {id:"service-update", date:"—", kz:{title:"Жаңалық жариялау үлгісі",body:"Бұл тек жаңалық карточкасының үлгісі, ресми жарияланым емес."},ru:{title:"Пример публикации новости",body:"Это только образец карточки новости, а не официальная публикация."}},
];

export const officialNews = [
  {id:"water-workers-2026",date:"20.07.2026",source:sourceLinks.newsWorkers,kz:{title:"Су шаруашылығы қызметкерлеріне құрмет көрсетілді",body:"Қала әкімі су шаруашылығы мамандарын кәсіби мерекесімен құттықтап, бірқатар қызметкерлерді марапаттады."},ru:{title:"Работникам водного хозяйства выразили признательность",body:"Аким города поздравил работников водного хозяйства с профессиональным праздником и вручил награды ряду специалистов."}},
  {id:"openness-meeting-2026",date:"11.06.2026",source:sourceLinks.newsOpenness,kz:{title:"Ашықтық қағидатына бағытталған кездесу",body:"Кәсіпорынның комплаенс-офицері ұжыммен кәсіби этика, ашықтық және сыбайлас жемқорлыққа қарсы талаптар туралы кездесу өткізді."},ru:{title:"Встреча, посвящённая принципу открытости",body:"Комплаенс-офицер предприятия обсудил с коллективом профессиональную этику, открытость и антикоррупционные требования."}},
  {id:"activity-report-2026",date:"2026",source:sourceLinks.report2026,kz:{title:"2026 жылғы мамыр–маусымдағы қызмет есебі",body:"Кәсіпорын ауыз су беру, сарқынды суды бұру, инвестициялық бағдарлама және жөндеу жұмыстары туралы есеп жариялады."},ru:{title:"Отчёт о деятельности за май–июнь 2026 года",body:"Предприятие опубликовало отчёт о подаче питьевой воды, водоотведении, инвестиционной программе и ремонтных работах."}},
  {id:"tariff-document-2026",date:"25.05.2026–30.04.2027",source:sourceLinks.tariff2026,kz:{title:"2026–2027 жылдарға арналған тариф құжаты",body:"Кәсіпорын суды тарату және сарқынды суды бұру мен тазарту тарифтеріне қатысты құжатты жариялады. Нақты сомалар бастапқы PDF құжатында көрсетілген."},ru:{title:"Документ о тарифах на 2026–2027 годы",body:"Предприятие опубликовало документ о тарифах на подачу воды и отвод и очистку сточных вод. Точные суммы указаны в исходном PDF."}},
] as const;
